// Generated by CoffeeScript 1.6.3
(function() {
  var get, getit, isObject, pathFn;

  pathFn = function(obj, path, def) {
    var part, _i, _len, _ref;
    _ref = path.split('.');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      part = _ref[_i];
      if (!obj || typeof obj !== 'object') {
        return def;
      }
      obj = obj[part];
    }
    if (obj === void 0) {
      return def;
    }
    return obj;
  };

  isObject = function(value) {
    var _ref;
    if (value == null) {
      return false;
    }
    if (typeof value !== 'object') {
      return false;
    }
    return ((_ref = value.constructor) != null ? _ref.name : void 0) === 'Object';
  };

  get = function(path) {
    var value;
    value = pathFn(this, path);
    if (isObject(value)) {
      getit(value);
    }
    return value;
  };

  module.exports = getit = function(obj) {
    if (obj == null) {
      return obj;
    }
    if (!isObject(obj)) {
      throw 'Not an Object';
    }
    Object.defineProperty(obj, 'get', {
      value: get,
      enumerable: false
    });
    return obj;
  };

}).call(this);
