// Generated by CoffeeScript 1.6.3
(function() {
  var get, getit, isObject, pathFn;

  pathFn = function(obj, path) {
    var part, _i, _len, _ref;
    _ref = path.split('.');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      part = _ref[_i];
      if ((obj == null) || typeof obj !== 'object') {
        return obj;
      }
      obj = obj[part];
    }
    return obj;
  };

  isObject = function(value) {
    if (value == null) {
      return false;
    }
    if (typeof value !== 'object') {
      return false;
    }
    return value.constructor === Object;
  };

  get = function(path) {
    var item, value, _i, _len;
    value = pathFn(this, path);
    if (isObject(value)) {
      getit(value);
    }
    if (Array.isArray(value)) {
      for (_i = 0, _len = value.length; _i < _len; _i++) {
        item = value[_i];
        if (isObject(item)) {
          getit(item);
        }
      }
    }
    return value;
  };

  module.exports = getit = function(obj) {
    if (obj == null) {
      return obj;
    }
    if (!isObject(obj)) {
      throw 'Not an Object';
    }
    Object.defineProperty(obj, 'get', {
      value: get,
      enumerable: false
    });
    return obj;
  };

}).call(this);
