// Generated by CoffeeScript 1.6.3
(function() {
  var get, modelit, pathFn;

  pathFn = function(obj, path, def) {
    var part, _i, _len, _ref;
    _ref = path.split('.');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      part = _ref[_i];
      if (!obj || typeof obj !== 'object') {
        return def;
      }
      obj = obj[part];
    }
    if (obj === void 0) {
      return def;
    }
    return obj;
  };

  get = function(path) {
    return pathFn(this, path);
  };

  module.exports = modelit = function(obj) {
    var _ref;
    if (obj == null) {
      return obj;
    }
    if (((_ref = obj.constructor) != null ? _ref.name : void 0) !== 'Object') {
      throw 'Not an Object';
    }
    Object.defineProperty(obj, 'get', {
      value: get,
      enumerable: false
    });
    return obj;
  };

}).call(this);
